package server

import (
	"errors"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"curated-backend/internal/backup"
	"curated-backend/internal/config"
	"curated-backend/internal/contracts"
)

const maxBackupUploadBytes int64 = 8 << 30

func (h *Handler) backupDestinationDirectory() string {
	directory := strings.TrimSpace(h.cfg.BackupDirectory)
	if h.backupDirectoryCtl != nil {
		directory = strings.TrimSpace(h.backupDirectoryCtl.BackupDirectory())
	}
	if directory == "" {
		directory = config.DefaultBackupDirectory()
	}
	return directory
}

// Only the configured backup directory and its managed import folder are read.
// Choosing a default never verifies, modifies or restores the package.
func (h *Handler) handleLatestBackup(w http.ResponseWriter, r *http.Request) {
	directory := h.backupDestinationDirectory()
	latest := contracts.BackupFileSelectionDTO{}
	var modified time.Time
	for _, root := range []string{directory, filepath.Join(directory, "imports")} {
		entries, err := os.ReadDir(root)
		if errors.Is(err, os.ErrNotExist) {
			continue
		}
		if err != nil {
			writeAppError(w, http.StatusBadRequest, contracts.ErrorCodeBackupInvalidRequest, "could not read backup directory")
			return
		}
		for _, entry := range entries {
			if entry.IsDir() || entry.Type()&os.ModeSymlink != 0 || !strings.HasSuffix(strings.ToLower(entry.Name()), ".curated-backup") {
				continue
			}
			info, err := entry.Info()
			if err != nil || !info.Mode().IsRegular() {
				continue
			}
			if latest.BackupPath == "" || info.ModTime().After(modified) {
				absolute, err := filepath.Abs(filepath.Join(root, entry.Name()))
				if err != nil {
					continue
				}
				latest.BackupPath, modified = absolute, info.ModTime()
			}
		}
	}
	writeJSON(w, http.StatusOK, latest)
}

// Browser File objects do not expose local paths. Stream the selected package
// into a private, uniquely named file; only retain packages passing verification
// so the returned path remains available for the existing offline restore flow.
func (h *Handler) handleInspectBackupFile(w http.ResponseWriter, r *http.Request) {
	if h.backupProvider == nil {
		writeAppError(w, http.StatusServiceUnavailable, contracts.ErrorCodeBackupPreflightFailed, "backup service is unavailable")
		return
	}
	defer r.Body.Close()
	r.Body = http.MaxBytesReader(w, r.Body, maxBackupUploadBytes+(1<<20))
	reader, err := r.MultipartReader()
	if err != nil {
		writeAppError(w, http.StatusBadRequest, contracts.ErrorCodeBackupInvalidRequest, "select a .curated-backup file")
		return
	}
	part, err := reader.NextPart()
	if err != nil || part.FormName() != "file" || !strings.HasSuffix(strings.ToLower(part.FileName()), ".curated-backup") {
		writeAppError(w, http.StatusBadRequest, contracts.ErrorCodeBackupInvalidRequest, "select a .curated-backup file")
		return
	}
	directory := filepath.Join(h.backupDestinationDirectory(), "imports")
	if err := os.MkdirAll(directory, 0o700); err != nil {
		writeAppError(w, http.StatusInternalServerError, contracts.ErrorCodeBackupPreflightFailed, "could not prepare backup import directory")
		return
	}
	file, err := os.CreateTemp(directory, "import-*.tmp")
	if err != nil {
		writeAppError(w, http.StatusInternalServerError, contracts.ErrorCodeBackupPreflightFailed, "could not save selected backup")
		return
	}
	temporary := file.Name()
	defer os.Remove(temporary)
	defer file.Close()
	size, err := io.Copy(file, io.LimitReader(part, maxBackupUploadBytes+1))
	if size > maxBackupUploadBytes {
		writeAppError(w, http.StatusRequestEntityTooLarge, contracts.ErrorCodeBackupInvalidRequest, "backup file exceeds the 8 GiB upload limit")
		return
	}
	if err != nil || size == 0 {
		writeAppError(w, http.StatusBadRequest, contracts.ErrorCodeBackupInvalidRequest, "backup upload was empty or interrupted")
		return
	}
	if _, err := reader.NextPart(); !errors.Is(err, io.EOF) {
		writeAppError(w, http.StatusBadRequest, contracts.ErrorCodeBackupInvalidRequest, "select exactly one backup file")
		return
	}
	if err := file.Sync(); err != nil {
		writeAppError(w, http.StatusInternalServerError, contracts.ErrorCodeBackupPreflightFailed, "could not save selected backup")
		return
	}
	if err := file.Close(); err != nil {
		writeAppError(w, http.StatusInternalServerError, contracts.ErrorCodeBackupPreflightFailed, "could not finish saving selected backup")
		return
	}
	preflight, err := h.backupProvider.PreflightBackupRestore(r.Context(), temporary)
	if err != nil {
		writeAppError(w, http.StatusBadRequest, contracts.ErrorCodeBackupPreflightFailed, "failed to read or verify the selected backup")
		return
	}
	result := contracts.BackupFileInspectionDTO{Preflight: preflight}
	if preflight.Verification.Valid {
		// The random filename is generated by Server; uploaded names never form paths.
		destination := strings.TrimSuffix(temporary, ".tmp") + ".curated-backup"
		if err := backup.RetainVerifiedPackage(temporary, destination); err != nil {
			writeAppError(w, http.StatusInternalServerError, contracts.ErrorCodeBackupPreflightFailed, "could not retain verified backup")
			return
		}
		result.BackupPath, err = filepath.Abs(destination)
		if err != nil {
			writeAppError(w, http.StatusInternalServerError, contracts.ErrorCodeBackupPreflightFailed, "could not resolve verified backup path")
			return
		}
	}
	writeJSON(w, http.StatusOK, result)
}
