import { flushPromises, mount } from "@vue/test-utils"
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest"
import { ref } from "vue"
import type { AIProviderSettingsDTO } from "@/api/types"
import { defaultAIGovernance, type AIGovernanceSettings, type AIReport, type AIPage, type AIAuditEntry } from "@/services/contracts/ai-governance-service"
import SettingsAISection from "./SettingsAISection.vue"
import { applyAIGovernance, useExperimentalAgent } from "@/lib/experimental-agent"

const mocks = vi.hoisted(() => ({ getSettings: vi.fn(), saveSettings: vi.fn(), getUsage: vi.fn(), getAudit: vi.fn(), cleanup: vi.fn(), setAIProvider: vi.fn(), testAIProvider: vi.fn() }))
const providerState = ref<AIProviderSettingsDTO>({ kind: "openai-compatible", baseUrl: "", model: "" })
vi.mock("@/services/ai-governance-service", () => ({ useAIGovernanceService: () => mocks }))
vi.mock("@/services/library-service", () => ({ useLibraryService: () => ({ aiProvider: providerState, setAIProvider: mocks.setAIProvider, testAIProvider: mocks.testAIProvider }) }))
vi.mock("vue-i18n", () => ({ useI18n: () => ({ locale: ref("en"), t: (key: string, params?: { message?: string }) => params?.message ? `${key}: ${params.message}` : key }) }))

function emptyReport(): AIReport {
  return { items: [], total: 0, limit: 5, offset: 0, summary: { runs: 0, failed: 0, partial: 0, cancelled: 0, modelCalls: 0, usageCalls: 0, toolCalls: 0, promptTokens: 0, completionTokens: 0, totalTokens: 0, avgDurationMs: null, avgFirstTextMs: null } }
}
async function setup() { const wrapper = mount(SettingsAISection, { props: { useWebApi: true } }); await flushPromises(); return wrapper }
function paginatedRecords() {
  const report = emptyReport()
  report.total = 7
  report.items = Array.from({ length: 5 }, (_, index) => ({ id: `run-${index}`, startedAt: "2026-09-06T00:00:00Z", channel: "chat", action: "", sessionId: "", provider: "test", model: "model", promptVersion: "v1", status: "completed", errorCode: "", durationMs: 12, firstTextMs: 4, modelCalls: 1, usageCalls: 1, toolCalls: 0, promptTokens: 2, completionTokens: 3, totalTokens: 5 }))
  const audit: AIPage<AIAuditEntry> = { items: Array.from({ length: 10 }, (_, index) => ({ id: `audit-${index}`, createdAt: "2026-09-06T00:00:00Z", channel: "chat", sessionId: "", tool: "search_movies", permission: "read", result: "ok", errorCode: "", durationMs: 1 })), total: 12, limit: 10, offset: 0 }
  mocks.getUsage.mockResolvedValue(report)
  mocks.getAudit.mockResolvedValue(audit)
  return { report, audit }
}
beforeEach(() => {
  vi.useFakeTimers({ toFake: ["setTimeout", "clearTimeout"] })
  vi.clearAllMocks()
  providerState.value = { kind: "openai-compatible", baseUrl: "", model: "" }
  applyAIGovernance(defaultAIGovernance())
  mocks.getSettings.mockResolvedValue(defaultAIGovernance())
  mocks.saveSettings.mockImplementation(async (value) => value)
  mocks.getUsage.mockResolvedValue(emptyReport())
  mocks.getAudit.mockResolvedValue({ items: [], total: 0, limit: 10, offset: 0 })
  mocks.cleanup.mockResolvedValue({ runs: 2, audit: 1, receipts: 0 })
  mocks.setAIProvider.mockImplementation(async (value) => { providerState.value = { kind: "openai-compatible", ...value } })
  mocks.testAIProvider.mockResolvedValue({ ok: true, latencyMs: 10 })
})
afterEach(() => { vi.useRealTimers(); vi.restoreAllMocks() })
describe("SettingsAISection", () => {
  it("keeps provider configuration available while AI is disabled and shows unknown usage", async () => {
    const wrapper = await setup()
    expect(wrapper.find("#ai-base").exists()).toBe(true)
    expect(wrapper.get("[data-ai-token-total]").text()).toBe("aiSettings.unknown")
    expect(useExperimentalAgent().enabled.value).toBe(false)
    expect(wrapper.find("[data-ai-save]").exists()).toBe(false)
    expect(wrapper.find("[data-ai-provider-save]").exists()).toBe(false)
    expect(mocks.saveSettings).not.toHaveBeenCalled()
    expect(mocks.setAIProvider).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it("organizes governance, provider, and records into the settings card hierarchy", async () => {
    const wrapper = await setup()
    expect(wrapper.find("[data-ai-governance-card]").exists()).toBe(true)
    expect(wrapper.find("[data-ai-provider-card]").exists()).toBe(true)
    expect(wrapper.find("[data-ai-statistics-card]").exists()).toBe(true)
    expect(wrapper.find("[data-ai-settings-block=policy]").exists()).toBe(true)
    expect(wrapper.find("[data-ai-settings-block=limits]").exists()).toBe(true)
    expect(wrapper.find("[data-ai-settings-block=filters]").exists()).toBe(true)
    expect(wrapper.find("[data-ai-settings-block=recent-runs]").exists()).toBe(true)
    expect(wrapper.find("[data-ai-settings-block=audit]").exists()).toBe(true)
    wrapper.unmount()
  })
  it("keeps limit fields wide enough for their labels at intermediate settings widths", async () => {
    const wrapper = await setup()
    expect(wrapper.get("[data-ai-limit-fields]").classes()).toContain("grid-cols-[repeat(auto-fit,minmax(min(100%,20rem),1fr))]")
    wrapper.unmount()
  })
  it("loads five recent requests and ten audit records per page", async () => {
    const wrapper = await setup()
    expect(mocks.getUsage).toHaveBeenLastCalledWith(expect.objectContaining({ limit: 5, offset: 0 }))
    expect(mocks.getAudit).toHaveBeenLastCalledWith(expect.objectContaining({ limit: 10, offset: 0 }))
    wrapper.unmount()
  })
  it.each(["runs", "audit"] as const)("keeps content mounted while paging %s and only fetches that list", async (kind) => {
    const { report, audit } = paginatedRecords()
    const wrapper = await setup()
    const block = wrapper.get(`[data-ai-settings-block=${kind === "runs" ? "recent-runs" : "audit"}]`)
    const list = block.get("ul")
    const measuredHeight = kind === "runs" ? 204 : 414
    vi.spyOn(list.element, "getBoundingClientRect").mockReturnValue({ height: measuredHeight } as DOMRect)
    const summaryElement = wrapper.get("[data-ai-summary]").element
    const rowsBefore = wrapper.findAll("[data-ai-run-row], [data-ai-audit-row]").map(row => row.element)
    const nextButton = block.findAll("button").at(-1)!
    let resolvePage!: (value: AIReport | AIPage<AIAuditEntry>) => void
    const pending = new Promise<AIReport | AIPage<AIAuditEntry>>(resolve => { resolvePage = resolve })
    const target = kind === "runs" ? mocks.getUsage : mocks.getAudit
    target.mockReturnValueOnce(pending)
    await nextButton.trigger("click")
    expect(block.attributes("aria-busy")).toBe("true")
    expect(wrapper.get("[data-ai-summary]").element).toBe(summaryElement)
    expect(wrapper.findAll("[data-ai-run-row], [data-ai-audit-row]").map(row => row.element)).toEqual(rowsBefore)
    expect(nextButton.attributes("disabled")).toBeDefined()
    expect(mocks.getUsage).toHaveBeenCalledTimes(kind === "runs" ? 2 : 1)
    expect(mocks.getAudit).toHaveBeenCalledTimes(kind === "audit" ? 2 : 1)
    resolvePage(kind === "runs" ? { ...report, offset: 5, items: report.items.slice(0, 2) } : { ...audit, offset: 10, items: audit.items.slice(0, 2) })
    await flushPromises()
    expect(list.element.style.minHeight).toBe(`${measuredHeight}px`)
    expect(list.findAll("li")).toHaveLength(2)
    expect(nextButton.element).toBe(block.findAll("button").at(-1)!.element)
    expect(block.attributes("aria-busy")).toBe("false")
    wrapper.unmount()
  })
  it("keeps the current page after a paging error and retries the same offset", async () => {
    paginatedRecords()
    const wrapper = await setup()
    mocks.getUsage.mockRejectedValueOnce(new Error("page unavailable"))
    const block = wrapper.get("[data-ai-settings-block=recent-runs]")
    await block.findAll("button").at(-1)!.trigger("click"); await flushPromises()
    expect(block.get("[role=alert]").text()).toBe("page unavailable")
    expect(block.get("ul").findAll("li")).toHaveLength(5)
    expect(block.text()).toContain("1–5 / 7")
    expect(block.findAll("button")[0]!.attributes("disabled")).toBeDefined()
    await block.findAll("button").at(-1)!.trigger("click"); await flushPromises()
    expect(mocks.getUsage).toHaveBeenLastCalledWith(expect.objectContaining({ offset: 5 }))
    expect(mocks.getAudit).toHaveBeenCalledOnce()
    wrapper.unmount()
  })
  it("compacts request and audit records to one line with semantic status colors", async () => {
    const report = emptyReport()
    report.items = [{ id: "run-success", startedAt: "2026-09-06T00:00:00Z", channel: "chat", action: "", sessionId: "", provider: "test", model: "model", promptVersion: "v1", status: "completed", errorCode: "", durationMs: 12, firstTextMs: 4, modelCalls: 1, usageCalls: 1, toolCalls: 0, promptTokens: 2, completionTokens: 3, totalTokens: 5 }, { id: "run-failure", startedAt: "2026-09-06T00:00:00Z", channel: "chat", action: "", sessionId: "", provider: "test", model: "model", promptVersion: "v1", status: "failed", errorCode: "AI_FAILED", durationMs: 12, firstTextMs: null, modelCalls: 1, usageCalls: 0, toolCalls: 0, promptTokens: 0, completionTokens: 0, totalTokens: 0 }]
    mocks.getUsage.mockResolvedValue(report)
    mocks.getAudit.mockResolvedValue({ items: [{ id: "audit-success", createdAt: "2026-09-06T00:00:00Z", channel: "chat", sessionId: "", tool: "search_movies", permission: "read", result: "ok", errorCode: "", durationMs: 1 }, { id: "audit-failure", createdAt: "2026-09-06T00:00:00Z", channel: "chat", sessionId: "", tool: "search_movies", permission: "read", result: "error", errorCode: "AI_TOOL_FAILED", durationMs: 1 }], total: 2, limit: 25, offset: 0 })
    const wrapper = await setup()
    expect(wrapper.get('[data-ai-run-row="run-success"]').classes()).toContain("min-h-9")
    expect(wrapper.get('[data-ai-run-row="run-success"] [data-slot="badge"]').classes()).toContain("text-success")
    expect(wrapper.get('[data-ai-run-row="run-failure"] [data-slot="badge"]').classes()).toContain("text-danger")
    expect(wrapper.get('[data-ai-audit-row="audit-success"] [data-slot="badge"]').classes()).toContain("text-success")
    expect(wrapper.get('[data-ai-audit-row="audit-failure"] [data-slot="badge"]').classes()).toContain("text-danger")
    wrapper.unmount()
  })
  it("applies global state only after saving and keeps the old state on failure", async () => {
    const wrapper = await setup()
    mocks.saveSettings.mockRejectedValueOnce(new Error("offline"))
    await wrapper.get("[data-ai-enabled]").trigger("click")
    await flushPromises()
    expect(useExperimentalAgent().enabled.value).toBe(false)
    expect(wrapper.get("[role=alert]").text()).toContain("offline")
    await wrapper.get("[data-ai-policy-retry]").trigger("click"); await flushPromises()
    expect(mocks.saveSettings).toHaveBeenLastCalledWith({ ...defaultAIGovernance(), enabled: true })
    expect(useExperimentalAgent().enabled.value).toBe(true)
    wrapper.unmount()
  })
  it("marks partially reported usage and retries failed statistics loading", async () => {
    const report = emptyReport(); report.summary.modelCalls = 2; report.summary.usageCalls = 1; report.summary.totalTokens = 30
    mocks.getUsage.mockResolvedValue(report)
    const wrapper = await setup()
    expect(wrapper.get("[data-ai-token-total]").text()).toBe("30 (aiSettings.partialUsage)")
    mocks.getUsage.mockRejectedValueOnce(new Error("query failed"))
    await wrapper.get("[data-ai-refresh]").trigger("click"); await flushPromises()
    expect(wrapper.find("[data-ai-summary]").exists()).toBe(false)
    expect(wrapper.get("[role=alert]").text()).toContain("query failed")
    await wrapper.get("[data-ai-refresh]").trigger("click"); await flushPromises()
    expect(wrapper.find("[data-ai-summary]").exists()).toBe(true)
    wrapper.unmount()
  })
  it("debounces numeric changes and saves them without refreshing statistics", async () => {
    const wrapper = await setup()
    await wrapper.get("#ai-steps").setValue("2")
    await vi.advanceTimersByTimeAsync(300)
    await wrapper.get("#ai-steps").setValue("20")
    await vi.advanceTimersByTimeAsync(500)
    expect(mocks.saveSettings).not.toHaveBeenCalled()
    await vi.advanceTimersByTimeAsync(50)
    expect(mocks.saveSettings).toHaveBeenCalledExactlyOnceWith({ ...defaultAIGovernance(), stepLimit: 20 })
    expect(wrapper.get("[data-ai-policy-save-status]").text()).toContain("settings.autoPersistSaved")
    expect(mocks.getUsage).toHaveBeenCalledOnce()
    expect(mocks.getAudit).toHaveBeenCalledOnce()
    wrapper.unmount()
  })
  it("serializes policy changes and never replaces a newer draft with an older response", async () => {
    const wrapper = await setup()
    let finish!: (value: AIGovernanceSettings) => void
    mocks.saveSettings.mockReturnValueOnce(new Promise<AIGovernanceSettings>(resolve => { finish = resolve }))
    await wrapper.get("[data-ai-enabled]").trigger("click")
    await wrapper.get("#ai-steps").setValue("21")
    await wrapper.get("[data-ai-enabled]").trigger("click")
    await vi.advanceTimersByTimeAsync(600)
    expect(mocks.saveSettings).toHaveBeenCalledTimes(1)
    finish({ ...defaultAIGovernance(), enabled: true })
    await flushPromises()
    expect(mocks.saveSettings).toHaveBeenCalledTimes(2)
    expect(mocks.saveSettings).toHaveBeenLastCalledWith({ ...defaultAIGovernance(), stepLimit: 21 })
    expect((wrapper.get("#ai-steps").element as HTMLInputElement).value).toBe("21")
    expect(useExperimentalAgent().enabled.value).toBe(false)
    wrapper.unmount()
  })
  it("automatically saves provider drafts and retains failed edits for retry", async () => {
    const wrapper = await setup()
    mocks.setAIProvider.mockRejectedValueOnce(new Error("offline"))
    await wrapper.get("#ai-base").setValue("http://localhost:11434/v1")
    await wrapper.get("#ai-model").setValue("local-model")
    await vi.advanceTimersByTimeAsync(550)
    expect(mocks.setAIProvider).toHaveBeenCalledExactlyOnceWith({ baseUrl: "http://localhost:11434/v1", model: "local-model", apiKey: "" })
    expect((wrapper.get("#ai-model").element as HTMLInputElement).value).toBe("local-model")
    expect(wrapper.get("[data-ai-provider-save-status]").text()).toContain("offline")
    await wrapper.get("[data-ai-provider-retry]").trigger("click"); await flushPromises()
    expect(wrapper.get("[data-ai-provider-save-status]").text()).toContain("settings.autoPersistSaved")
    expect(mocks.testAIProvider).not.toHaveBeenCalled()
    wrapper.unmount()
  })
  it("flushes pending text edits on blur and before leaving the settings section", async () => {
    const wrapper = await setup()
    await wrapper.get("#ai-model").setValue("first-model")
    await wrapper.get("#ai-model").trigger("blur"); await flushPromises()
    expect(mocks.setAIProvider).toHaveBeenLastCalledWith({ baseUrl: "", model: "first-model", apiKey: "" })
    await wrapper.get("#ai-model").setValue("latest-model")
    await wrapper.get("#ai-steps").setValue("22")
    wrapper.unmount()
    await flushPromises()
    expect(mocks.setAIProvider).toHaveBeenLastCalledWith({ baseUrl: "", model: "latest-model", apiKey: "" })
    expect(mocks.saveSettings).toHaveBeenLastCalledWith({ ...defaultAIGovernance(), stepLimit: 22 })
  })
  it("protects newer provider input from the service's optimistic updates and rollback", async () => {
    const wrapper = await setup()
    let rejectSave!: (error: Error) => void
    mocks.setAIProvider.mockImplementationOnce(async (value) => {
      const previous = providerState.value
      providerState.value = { kind: "openai-compatible", ...value }
      try { await new Promise<void>((_, reject) => { rejectSave = reject }) }
      catch (error) { providerState.value = previous; throw error }
    })
    await wrapper.get("#ai-model").setValue("first-model")
    await vi.advanceTimersByTimeAsync(550)
    await wrapper.get("#ai-model").setValue("latest-model")
    rejectSave(new Error("offline")); await flushPromises()
    expect((wrapper.get("#ai-model").element as HTMLInputElement).value).toBe("latest-model")
    await wrapper.get("[data-ai-provider-retry]").trigger("click"); await flushPromises()
    expect(mocks.setAIProvider).toHaveBeenLastCalledWith({ baseUrl: "", model: "latest-model", apiKey: "" })
    expect((wrapper.get("#ai-model").element as HTMLInputElement).value).toBe("latest-model")
    wrapper.unmount()
  })
  it("flushes the model draft before an explicit connectivity test", async () => {
    const wrapper = await setup()
    await wrapper.get("#ai-model").setValue("local-model")
    await wrapper.get("[data-ai-provider-test]").trigger("click"); await flushPromises()
    expect(mocks.setAIProvider).toHaveBeenCalledOnce()
    expect(mocks.testAIProvider).toHaveBeenCalledWith({ kind: "openai-compatible", baseUrl: "", apiKey: "", model: "local-model" })
    expect(mocks.setAIProvider.mock.invocationCallOrder[0]).toBeLessThan(mocks.testAIProvider.mock.invocationCallOrder[0]!)
    wrapper.unmount()
  })
  it("rejects invalid policy locally and only cleans expired records on explicit click", async () => {
    const wrapper = await setup()
    expect(mocks.cleanup).not.toHaveBeenCalled()
    await wrapper.get("#ai-retention").setValue("1")
    await vi.advanceTimersByTimeAsync(600)
    expect(mocks.saveSettings).not.toHaveBeenCalled()
    expect(wrapper.get("#ai-retention").attributes("aria-invalid")).toBe("true")
    expect(wrapper.get("[data-ai-policy-save-status]").text()).toContain("aiSettings.invalidLimits")
    await wrapper.get("[data-ai-cleanup]").trigger("click"); await flushPromises()
    expect(mocks.cleanup).toHaveBeenCalledOnce()
    wrapper.unmount()
  })
  it("preserves the provider failure after refreshing its recorded statistics", async () => {
    const wrapper = await setup()
    mocks.testAIProvider.mockResolvedValueOnce({ ok: false, message: "authentication failed" })
    await wrapper.get("[data-ai-provider-test]").trigger("click"); await flushPromises()
    const result = wrapper.get("[data-ai-provider-test-result]")
    expect(result.text()).toContain("settings.experimentalTestFail")
    expect(result.attributes("data-status")).toBe("failed")
    expect(wrapper.find("[data-ai-settings-error]").exists()).toBe(false)
    expect(mocks.getUsage).toHaveBeenCalledTimes(2)
    wrapper.unmount()
  })
  it("renders a successful connectivity test inside the model provider section", async () => {
    const wrapper = await setup()
    await wrapper.get("[data-ai-provider-test]").trigger("click"); await flushPromises()
    const provider = wrapper.get("[data-ai-provider-card]")
    const result = provider.get("[data-ai-provider-test-result]")
    expect(result.text()).toBe("settings.experimentalTestOk")
    expect(result.attributes("data-status")).toBe("success")
    expect(result.classes()).toContain("text-success")
    wrapper.unmount()
  })
})
