ALTER TABLE actors ADD COLUMN summary TEXT NOT NULL DEFAULT '';
ALTER TABLE actors ADD COLUMN homepage TEXT NOT NULL DEFAULT '';
ALTER TABLE actors ADD COLUMN provider TEXT NOT NULL DEFAULT '';
ALTER TABLE actors ADD COLUMN provider_actor_id TEXT NOT NULL DEFAULT '';
ALTER TABLE actors ADD COLUMN height INTEGER NOT NULL DEFAULT 0;
ALTER TABLE actors ADD COLUMN birthday TEXT NOT NULL DEFAULT '';
ALTER TABLE actors ADD COLUMN profile_updated_at TEXT NOT NULL DEFAULT '';
