import { flushPromises, mount } from "@vue/test-utils"
import { ref } from "vue"
import { beforeEach, describe, expect, it, vi } from "vitest"
import BookPagePreviewGrid from "./BookPagePreviewGrid.vue"
const width = ref(792)
vi.mock("@vueuse/core", async original => ({ ...await original<typeof import("@vueuse/core")>(), useElementSize: () => ({width, height: ref(0)}) }))
vi.mock("vue-i18n", () => ({useI18n: () => ({t: (key: string) => key})}))
const pages = Array.from({length: 1000}, (_, index) => ({index, thumbUrl: `/thumb/${index}`}))
beforeEach(() => { width.value = 792 })
describe("adaptive book previews", () => {
  it("sizes two rows to container width and bounds DOM even for a thousand pages", async () => {
    const wrapper = mount(BookPagePreviewGrid, {props: {bookId: "a", pages, total: 1000, kind: "photos"}})
    expect(wrapper.findAll('[data-book-preview-tile]')).toHaveLength(12)
    width.value = 300; await flushPromises()
    expect(wrapper.findAll('[data-book-preview-tile]')).toHaveLength(4)
    width.value = 3000; await flushPromises()
    expect(wrapper.findAll('[data-book-preview-tile]')).toHaveLength(20)
    wrapper.unmount()
  })
  it("navigates numbered batches, opens the last image and resets for another book", async () => {
    const wrapper = mount(BookPagePreviewGrid, {props: {bookId: "a", pages, total: 1000, kind: "comics"}})
    await wrapper.get('[data-preview-next]').trigger('click')
    expect(wrapper.findAll('[data-book-preview-tile]')[0]!.text()).toBe('13')
    await wrapper.get('[data-preview-previous]').trigger('click')
    expect(wrapper.findAll('[data-book-preview-tile]')[0]!.text()).toBe('1')
    expect(wrapper.find('input').exists()).toBe(false)
    expect(wrapper.find('form').exists()).toBe(false)
    expect(wrapper.get('[data-preview-batch="1"]').attributes('aria-current')).toBe('page')
    await wrapper.get('[data-preview-batch="84"]').trigger('click')
    expect(wrapper.findAll('[data-book-preview-tile]')).toHaveLength(4)
    expect(wrapper.get<HTMLButtonElement>('[data-preview-next]').element.disabled).toBe(true)
    await wrapper.findAll('[data-book-preview-tile]').at(-1)!.trigger('click')
    expect(wrapper.emitted('open')).toEqual([[999]])
    await wrapper.setProps({bookId: 'b', pages: pages.slice(0,2), total: 2})
    expect(wrapper.findAll('[data-book-preview-tile]')[0]!.text()).toBe('1')
    expect(wrapper.get('[data-preview-batch="1"]').attributes('aria-current')).toBe('page')
    expect(wrapper.findAll('[data-preview-batch]')).toHaveLength(1)
    expect(wrapper.get<HTMLButtonElement>('[data-preview-previous]').element.disabled).toBe(true)
    expect(wrapper.get<HTMLButtonElement>('[data-preview-next]').element.disabled).toBe(true)
    wrapper.unmount()
  })
  it("keeps pagination compact with ellipses and preserves the image anchor when resized", async () => {
    const wrapper = mount(BookPagePreviewGrid, {props: {bookId: "a", pages, total: 1000, kind: "photos"}})
    expect(wrapper.findAll('[data-preview-batch]').map(item => item.text())).toEqual(['1','2','3','4','5','84'])
    await wrapper.get('[data-preview-batch="5"]').trigger('click')
    expect(wrapper.findAll('[data-preview-batch]').map(item => item.text())).toEqual(['1','4','5','6','84'])
    expect(wrapper.findAll('[data-book-preview-tile]')[0]!.text()).toBe('49')
    width.value = 300
    await flushPromises()
    expect(wrapper.get('[data-preview-batch="13"]').attributes('aria-current')).toBe('page')
    expect(wrapper.findAll('[data-book-preview-tile]')).toHaveLength(4)
    expect(wrapper.findAll('[data-book-preview-tile]')[0]!.text()).toBe('49')
    expect(wrapper.findAll('[data-preview-batch]')).toHaveLength(3)
    await wrapper.get('[data-preview-batch="250"]').trigger('click')
    expect(wrapper.findAll('[data-book-preview-tile]')[0]!.text()).toBe('997')
    wrapper.unmount()
  })
  it("hides pagination for an empty book", () => {
    const wrapper = mount(BookPagePreviewGrid, {props: {bookId: "empty", pages: [], total: 0, kind: "photos"}})
    expect(wrapper.find('nav').exists()).toBe(false)
    wrapper.unmount()
  })
})
